services:
  - type: web
    plan: free
    name: FileS
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/Pradeep-iKp/FileS.git      
    branch: main
    envVars:
      - key: TG_BOT_TOKEN 
        sync: false
      - key: APP_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: CHANNEL_ID 
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ADMINS 
        sync: false   
    autoDeploy: false 
